import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro", // This should match the id of your main doc (intro.md)
      label: "Introduction", // This will be the label in the sidebar
    },
    // You can add more entries here for other pages or categories
  ],
};

export default sidebars;
